version: "2"
networks:
    mongo_network:
        driver: bridge
services:
    mongo_service:
        image: mongo:5.0
        ports:
            - 27017:27017
        volumes:
            - ./docker/mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=zowt
            - MONGO_INITDB_ROOT_PASSWORD=zowt
        networks:
            - mongo_network
    app:
        build: 
          # Build an image from the Dockerfile in the current directory
          context: .
        ports:
          - 5000:5000
        environment:
          PORT: 5000
          BASE: 0.0.0.0
        depends_on:
            - mongo_service
        networks:
            - mongo_network
        environment:
            - USER=zowt
            - PASSWORD=zowt
            - DATABASE=mongo
